### ISSUE TITLE
Installation using wheel is broken

### ISSUE THREAD

**Issue by QuentinFra** [Ezibenroc/PyRoaringBitMap#23] opened 2017-09-18 19:56 UTC
Hi,

We plan to use this library at Datadog (https://github.com/DataDog) and we use wheels to install the Python libs. While trying to install `pyroaring`, I found out that it doesn't work when using wheel as the `roaring.hh` header file isn't included in the wheel:
```
qf~$ sudo pip wheel pyroaring
qf~$ unzip pyroaring-0.1.5-cp27-cp27mu-linux_x86_64.whl
Archive:  pyroaring-0.1.5-cp27-cp27mu-linux_x86_64.whl
  inflating: pyroaring.so
  inflating: pyroaring-0.1.5.dist-info/DESCRIPTION.rst
  inflating: pyroaring-0.1.5.dist-info/metadata.json
  inflating: pyroaring-0.1.5.dist-info/top_level.txt
  inflating: pyroaring-0.1.5.dist-info/WHEEL
  inflating: pyroaring-0.1.5.dist-info/METADATA
  inflating: pyroaring-0.1.5.dist-info/RECORD
```

The fix I found is to explicitely set the required headers in `setup()`: https://github.com/DataDog/PyRoaringBitMap/commit/ed652576556509141d31077a3e4967503110533a. Can I submit this fix or could you take look when you get a chance? 

Thanks,
Quentin

**Comment by Ezibenroc** [comment] 2017-09-19 08:07
Hello,

I am not familiar with wheels. Could you tell me what is the issue here?
I tried to install pyroaring like this and it seems to work fine:
```
$ mkdir test && cd test
$ python -c 'import pyroaring'     
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pyroaring
$ pip wheel pyroaring
Collecting pyroaring
  Using cached pyroaring-0.1.5.tar.gz
Building wheels for collected packages: pyroaring
  Running setup.py bdist_wheel for pyroaring ... done
  Stored in directory: /home/tom/test
Successfully built pyroaring
$ ls
pyroaring-0.1.5-cp27-cp27mu-linux_x86_64.whl
$ pip install --user pyroaring-0.1.5-cp27-cp27mu-linux_x86_64.whl
Processing ./pyroaring-0.1.5-cp27-cp27mu-linux_x86_64.whl
Installing collected packages: pyroaring
Successfully installed pyroaring-0.1.5
$ python -c 'import pyroaring'
```
Am I missing something?

**Comment by QuentinFra** [comment] 2017-09-19 13:29
Hi,

Yes forget what I said, looks like it works fine (I got fooled by Python cache while debugging the issue). But for some reason it doesn't work on the machines where we build our wheels, I'll investigate further and post an update here later today.

Thanks,
Quentin

**Comment by QuentinFra** [comment] 2017-09-19 14:03
Btw, that's why I see in the debugger when running a simple Python script that creates a bitmap when pyroaring was installed with the bad wheel:
```
(gdb) run test.py
Starting program: /usr/bin/python test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Program received signal SIGILL, Illegal instruction.
bitset_container_set (pos=0, bitset=0x9e38a0) at roaring.hh:1564
1564    roaring.hh: No such file or directory.
```

**Comment by lemire** [comment] 2017-09-19 15:57
@QuentinFra  This error message is not caused by the failure of finding roaring.hh, it is caused by the "illegal instruction". 

This, in turn, tends to happen when your binaries don't match your hardware (e.g., either you using old software on newer hardware, or the reverse).

**Comment by QuentinFra** [comment] 2017-09-19 21:45
@lemire Thanks, looks like you're right: the wheel works fine on the box where it was produced, but doesn't work on other boxes where it is supposed to be used.

**Comment by lemire** [comment] 2017-09-19 22:18
Can you install on each machine?

**Comment by QuentinFra** [comment] 2017-09-19 22:33
Yes, the installation works fine on each machine, but when I try to run a basic python script that creates a Bitmap, I get the error I posted above.

**Comment by lemire** [comment] 2017-09-19 23:07
I meant: install without wheel.

The current setup.py could have a flag generating untargetted builds (-march=x86 or -march=x86-64) which you could pass to the setup.py via --global-options as per the wheel spec.

**Comment by lemire** [comment] 2017-09-20 02:16
@Ezibenroc Any chance setup.py could have an extra flag allowing users to specify the hardware target?

**Comment by Ezibenroc** [comment] 2017-09-20 11:17
A tentative here: https://github.com/Ezibenroc/PyRoaringBitMap/commit/96442d4c05ce4b258e307148b204e1c7449e26b9

I think something like this should work for you:
```bash
ARCHI=x86-64 python setup.py bdist_wheel
pip install --user /path/to/the/wheel
```

However, it does not work if you want to compile for a 32-bit architecture from a 64-bit architecture. For instance, this fails:
```bash
ARCHI=i386 python3 setup.py bdist_wheel
```

@QuentinFra Can you test and tell me if this works for your use case?


@lemire I had to force the option `-DDISABLE_X64` to compile with something else than `-march=native`. Otherwise, I have compilation errors such as:
```
/usr/lib/gcc/x86_64-linux-gnu/6/include/smmintrin.h:288:1: error: inlining failed in call to always_inline ‘__m128i _mm_min_epu16(__m128i, __m128i)’: target specific option mismatch
 _mm_min_epu16 (__m128i __X, __m128i __Y)
```
This seems to happen for any other cpu-type, e.g. `x86-64`. Is it expected?

**Comment by lemire** [comment] 2017-09-20 15:18
Yes. So basically, I think that x86-64 assumes SSE2 but no better, which sets us back 20 years ago. I'll push an update.

I think one needs to be aware that compiling code this way basically sets us back 20 years hardware wise. So the performance is going to suffer, there is no way around this.

It would be much better to compile for the hardware you have.

**Comment by QuentinFra** [comment] 2017-09-20 19:58
@Ezibenroc I confirm that your change fixed my issue. Thanks for looking into this @Ezibenroc @lemire! For now, I mirrored your fix on my fork and will use that until the next release.

**Comment by lemire** [comment] 2017-09-20 22:23
I’ll issue a minor release to help with this issue soon.

**Comment by lemire** [comment] 2017-09-21 00:40
@Ezibenroc 

Can you verify that the requirement to add ``-DDISABLE_X64`` is gone?

**Comment by Ezibenroc** [comment] 2017-09-21 12:18
@lemire Yes, no more need to add `-DDISABLE_X64`, thanks!

@QuentinFra I made a new release, now closing the issue.

**Closed by Ezibenroc** 2017-09-21 12:18 UTC

**Comment by lemire** [comment] 2017-09-21 12:23
In the README, regarding march, you assume gcc, but it could be clang as well.
