### ISSUE TITLE
Provide prebuilt Windows wheel for Python 2.7

### ISSUE THREAD

**Issue by pombredanne** [Ezibenroc/PyRoaringBitMap#48] opened 2019-05-03 15:58 UTC
This is available for Python 3 but not 2.7. That would be quite nice to have it too as this seems  tad engaged to build from sources.

**Comment by lemire** [comment] 2019-05-03 21:42
@pombredanne Building for older versions of Python on Windows implies building with obsolete and now unsupported versions of Visual Studio. In turn, this forces us to cater to all of the limitations of obsolete compilers.

**Comment by pombredanne** [comment] 2019-05-03 22:07
@lemire fair enough, I was suspecting something along these lines. I will have a to wait a tad until we complete the Python 3 port of https://github.com/nexB/scancode-toolkit as I am looking to check if the heavy usage of integer bitmap could be a boost by using roaring bitmaps:  https://github.com/nexB/scancode-toolkit/blob/develop/thirdparty/intbitset-2.3.0.tar.gz.ABOUT

**Comment by lemire** [comment] 2019-05-03 22:14
Interesting.

As an indication... Big projects with more developers and money than God, like Pytorch, do not support Python 2 on Windows...
https://github.com/pytorch/pytorch

The problem is really upstream... old Python builds were not designed with future extensions in mind under Windows.

**Comment by Ezibenroc** [comment] 2019-05-06 07:54
As @lemire said, this is hard to do. I do not think that it is worth the effort, given that Python 2 official end of life is in less than a year.

I will close the issue, feel free to reopen if you somehow manage to do it.

**Closed** 2019-05-06 07:54 UTC
Labels: wontfix
