### ISSUE TITLE
Does not install from PyPi on Linux Ubuntu aarch64

### ISSUE THREAD

**Issue by FrankC01** [Ezibenroc/PyRoaringBitMap#87] opened 2023-03-27 19:22 UTC
I am running on Linux Ubuntu for aarch64

After installing (venv), neither are recognized in my source
```python
import pyroaring
# Or
from pyroaring import BitMap
```

I tried installing with both:
```bash
pip install pyroaring

# And

pip install --use-pep517 --no-cache-dir pyroaring
```

But when I do `pip show -f pyroaring` in see this:
```bash
$ pip show -f pyroaring
Name: pyroaring
Version: 0.4.0
Summary: Fast and lightweight set for unsigned 32 bits integers.
Home-page: https://github.com/Ezibenroc/PyRoaringBitMap
Author: Tom Cornebize
Author-email: tom.cornebize@gmail.com
License: MIT
Location: /home/fastfrank/frankc01/pysui/pysuienv/lib/python3.10/site-packages
Requires: 
Required-by: 
Files:
  pyroaring-0.4.0.dist-info/INSTALLER
  pyroaring-0.4.0.dist-info/LICENSE
  pyroaring-0.4.0.dist-info/METADATA
  pyroaring-0.4.0.dist-info/RECORD
  pyroaring-0.4.0.dist-info/REQUESTED
  pyroaring-0.4.0.dist-info/WHEEL
  pyroaring-0.4.0.dist-info/top_level.txt
  pyroaring.cpython-310-aarch64-linux-gnu.so
```

As I am intending to have this as a requirement for my SUI SDK `pysui` I need to ensure that Linux and macos users can install.

Any ideas?

**Comment by Ezibenroc** [comment] 2023-03-28 09:20
Your issue made me realize that we do not have a binary package available on Pypi for Python3.7 on MacOS. The reason is that it is not supported by [cibuildwheel](https://github.com/pypa/cibuildwheel), the tool we use for packaging.

-----

Anyway, this is not the cause of your problem, since you seem to use Python 3.10 and the package seem to install correctly.
I am confused by what you describe. Are you sure the `pip` and `python` you are using are from the same venv? You could even use `python -m pip` instead of `pip` to be extra-sure.

**Comment by Ezibenroc** [comment] 2023-03-28 09:22
You could also try an older pyroaring version, e.g. `pip uninstall pyroaring && pip install pyroaring==0.3.8`. But I don't think this would change anything.

**Comment by FrankC01** [comment] 2023-03-28 23:07
> Are you sure the pip and python you are using are from the same venv? You could even use python -m pip instead of pip to be extra-sure

Yes, verified that python and pip. I also used `python -m pip ...` and get the same results.

Python: 3.10.6
pip: 23.0.1

**Comment by lemire** [comment] 2023-03-29 03:50
@FrankC01  I cannot verify the issue.

<img width="951" alt="Capture d’écran, le 2023-03-28 à 23 48 35" src="https://user-images.githubusercontent.com/391987/228422018-0919be34-e5d0-4bc5-80f9-1b5250e54ea6.png">
<img width="954" alt="Capture d’écran, le 2023-03-28 à 23 48 03" src="https://user-images.githubusercontent.com/391987/228422024-6c319818-c997-4519-83d7-7f4f22a789b9.png">
<img width="974" alt="Capture d’écran, le 2023-03-28 à 23 48 23" src="https://user-images.githubusercontent.com/391987/228422023-3b291eb8-0ddf-4279-b814-71062bd56e88.png">

@Ezibenroc There are cheap ARM nodes on AWS, that's what I am using for this test.

**Comment by FrankC01** [comment] 2023-03-29 11:10
And, after the install, when you do a `pip show -f pyroaring`, what is the outcome?

**Comment by lemire** [comment] 2023-03-29 11:45
<img width="581" alt="Capture d’écran, le 2023-03-29 à 07 44 00" src="https://user-images.githubusercontent.com/391987/228525286-2424b24b-c1c7-415e-8490-3d3dad001b47.png">

**Comment by FrankC01** [comment] 2023-03-29 12:26
Ok, so I will wait for your fix then so that when users can install my SDK without having to force them to install a 'C' compiler (clang, etc.) correct?

**Comment by Ezibenroc** [comment] 2023-03-29 13:08
If your users are using Linux on ARM, yes waiting might be better.
Two points though, since I cannot guarantee if and when the ARM wheels for Linux will be available:
- You can build the wheel yourself and share it with your users (a `python setup.py bdist_wheel` should do the trick).
- It seems that some ARM wheels are automatically built for Raspberry Pi: https://www.piwheels.org/simple/pyroaring/
   I don't know this website and if it could suit your needs.

**Comment by FrankC01** [comment] 2023-03-29 19:25
Cool. I'll wait... I've a 'hack' workaround to keep me going.

It is needed to comply with a multi-sig transaction signing for the block-chain. The hack is I `subprocess` down to cmd-line and use their Rust binary signing tool.

**Comment by Ezibenroc** [comment] 2023-04-01 16:54
With the latest release (0.4.1), Linux and Windows wheels are available on Pypi for ARM.
@FrankC01 could you please test and tell me if it changes anything for you? Note that I don't think it will, since you already managed to install. I don't really understand what is happening here.

**Comment by FrankC01** [comment] 2023-04-01 17:24
Just tried it again
The only thing I see after, in the venv site packages, is the `dist-info` folder.

In vscode when I do a 'import pyroaring'... Go to Definition I get 'no definition found for pyroaring'

**Comment by Ezibenroc** [comment] 2023-04-02 19:31
I am sorry, but I cannot do much more to help you. This is the first time I see such problems. I tried on several systems (including fresh VMs from AWS) the following script, this worked as expected:
```sh
# Create and activate a virtualenv
python -m venv /tmp/test
source /tmp/test/bin/activate
# Install the latest pyroaring
pip install pyroaring
# Test that the installation is working
python -c 'import pyroaring ; print(pyroaring.__version__)'
# Cleanup
deactivate
rm -rf /tmp/test
```

Could you try the exact same script?

**Comment by FrankC01** [comment] 2023-04-02 19:46
I can and will.
I will also build/install from repo. This may be an ARM thing? The ubuntu I'm using may be a bit shaky as well. I'll suss it out a bit more and just comment findings here if thats OK?

**Comment by Ezibenroc** [comment] 2023-04-02 20:33
> I will also build/install from repo.

I recommand using a pre-compiled wheel from Pypi, this is the easiest (it requires the least dependencies). But you can try from the repo yes.

> This may be an ARM thing? The ubuntu I'm using may be a bit shaky as well.

I would suspect more your system here. For instance, a broken Python, this ecosystem can quickly become a mess (that's why everyone use virtualenv).
Have you tried installing another Python package you don't already have? Especially one with compiled code, like Numpy for instance.

> I'll suss it out a bit more and just comment findings here if thats OK?

Of course!

**Comment by FrankC01** [comment] 2023-04-02 21:58
Quick question, I'm not that strong on `pip` but how do I 'use a pre-compiled wheel' from PyPi?

As far as ARM... I trust the macos M1 versus Ubuntu VM more at the moment.

**Comment by Ezibenroc** [comment] 2023-04-03 06:36
> Quick question, I'm not that strong on pip but how do I 'use a pre-compiled wheel' from PyPi?

You look at the output from `pip install`, what kind of file it downloads. If it is a `*.tar.gz`, then it is the source package (which requires a C compiler), if it is a `*.whl` then it is a wheel (which is already compiled).

For instance, using `pip install pyroaring` in a virtualenv on my Mac M1:
- With Python 3.7 (for which there is no available wheel):
```
pip install pyroaring
Collecting pyroaring
  Downloading pyroaring-0.4.1.tar.gz (145 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 KB 8.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pyroaring, since package 'wheel' is not installed.
Installing collected packages: pyroaring
  Running setup.py install for pyroaring ... done
Successfully installed pyroaring-0.4.1
```
- With Python 3.10 (using a wheel):
```
pip install pyroaring
Collecting pyroaring
  Downloading pyroaring-0.4.1-cp310-cp310-macosx_11_0_arm64.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 kB 10.4 MB/s eta 0:00:00
Installing collected packages: pyroaring
Successfully installed pyroaring-0.4.1
```

If you want to be sure about which file is used for the installation, you can also copy the file URL [from this page](https://pypi.org/project/pyroaring/0.4.1/#files) and directly give the URL to `pip`. Be careful to select the right file (OS, Python version and architecture), or pip will not install anything. For instance, on a Mac M1 with Python 3.10:
```
pip install https://files.pythonhosted.org/packages/af/a9/4b6e2177bdd544be0ad2b870065ecf42119faf554b20e09365daf01a7285/pyroaring-0.4.1-cp310-cp310-macosx_11_0_arm64.whl
```

**Comment by FrankC01** [comment] 2023-04-03 09:27
> Could you try the exact same script?

On both macos and ubuntu, this is what I get:

```bash
fastfrank@~/frankc01/pysui $ . pysuienv/bin/activate
(pysuienv) fastfrank@~/frankc01/pysui $ code .
(pysuienv) fastfrank@~/frankc01/pysui $ pip install --no-cache pyroaring
Collecting pyroaring
  Downloading pyroaring-0.4.1-cp310-cp310-macosx_11_0_arm64.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 kB 3.4 MB/s eta 0:00:00
Installing collected packages: pyroaring
Successfully installed pyroaring-0.4.1
(pysuienv) fastfrank@~/frankc01/pysui $ python -c 'import pyroaring ; print(pyroaring.__version__)'
0.4.1
(pysuienv) fastfrank@~/frankc01/pysui $ python -c 'from pyroaring import BitMap; print(pyroaring.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pyroaring' is not defined
```

I haven't done the direct install you as you suggested yet.

**Comment by lemire** [comment] 2023-04-03 12:53
> `from pyroaring import BitMap; print(pyroaring.__version__)`

This is expected to give an error. If you do `pyroaring import BitMap`, you are importing `BitMap` but not `pyroaring`, so `pyroaring.__version__` should fail because `pyroaring` is undefined, and indeed it does.


Your last example suggests that everything works as expected.

**Comment by Ezibenroc** [comment] 2023-04-03 14:40
Indeed, this line shows that everything looks fine:
```
python -c 'import pyroaring ; print(pyroaring.__version__)'
0.4.1
```
With your second tentative, you could try this instead:
```
python -c 'from pyroaring import BitMap; print(BitMap([1,2,3]) & BitMap(range(10)))'
```
When you are at this step, you can also directly launch the Python interpreter by typing `python` and then import pyroaring.

**Comment by FrankC01** [comment] 2023-04-03 17:16
OK, that worked.

Then the the vscode may be a different issue (unable to see or show definitions)... I will try that later.

**Comment by Ezibenroc** [comment] 2023-04-03 20:09
Alright, nice! I am closing the issue then.

**Closed by Ezibenroc** 2023-04-03 20:09 UTC

**Comment by FrankC01** [comment] 2023-05-15 12:40
As a follow up, the VSCode issue, `pyroaring` is now part of `pysui` for the primary usage of generating a Roaring Bitmap as part of multi-sig signing.

The hidden gem is also the fact that `pyroaring` serializes as per https://github.com/RoaringBitmap/RoaringFormatSpec/

Thank you for your efforts!
